### ISSUE TITLE
Broken final release v3

### ISSUE THREAD

**Issue by cppforlife** [logsearch/logsearch-shipper-boshrelease#14]
@mrdavidlaing https://github.com/logsearch/logsearch-shipper-boshrelease/blob/master/.final_builds/packages/logsearch-nxlog/index.yml#L7 is missing a blobstore_id which gets automatically generated when creating a final release. you may be using an old bosh_cli that had a bug. currently bosh.io (or anyone) cannot produce final release v3.

**Comment by mrdavidlaing** [comment]
Thanks - I'll look into fixing that ASAP

**Comment by mrdavidlaing** [comment]
@cppforlife Hopefully fixed here: https://github.com/logsearch/logsearch-shipper-boshrelease/releases/tag/v4

**Comment by mrdavidlaing** [comment]
Yep - fixed - http://bosh.io/releases/github.com/logsearch/logsearch-shipper-boshrelease?version=4
