### ISSUE TITLE
remove v=3 final release since it cannot be built

### ISSUE THREAD

**Issue by cppforlife** [logsearch/logsearch-shipper-boshrelease#16]
Cannot find package with checksum `daa39cc56a3c1e7c1bd1e118cbb8ac5a08970df3'...

**Comment by mrdavidlaing** [comment]
@cppforlife Given the rise of cloudfoundry/syslog-boshrelease; I think the best course of action is to remove logsearch/logsearch-shipper-boshrelease from bosh.io
